name: products_automexa_apis
description: A sample command-line application.
version: 0.0.0
repository: https://github.com/automexa/products_automexa_apis
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  general_lib: ^0.0.21
  mason_logger: ^0.2.11
  path: ^1.9.0
  universal_io: ^2.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
