name: products_automexa_apis
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/automexa/products_automexa_apis
repository: https://github.com/automexa/products_automexa_apis
issue_tracker: https://github.com/automexa/products_automexa_apis/issues 
documentation: https://youtube.com/@automexa
funding:
  - https://github.com/sponsors/automexa


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - products_automexa_apis
#   - products_automexa_apis_flutter
#   - products_automexa_apis_dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
# dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
